project:
  type: book
  output-dir: pdf_output
execute:
  echo: false # This will hide the code
  output: true # This will show the output
  freeze: false # This will freeze the output
book:
  title: "Introduction to Computer-based Physical Modeling"
  author:
    name: "Frank Cichos"
    email: cichos@physik.uni-leipzig.de
    affiliation:
      - name: Leipzig University
        city: Leipzig
        url: http://www.uni-leipzig.de/~mona
  date: "8/14/2024"
  chapters:
    - index.qmd
    - part: "Lecture 1"
      chapters:
        - lectures/lecture01/00-lecture01.qmd
        - lectures/lecture01/01-lecture01.qmd
        - lectures/lecture01/python_lecture01.qmd
        - lectures/lecture01/02-lecture01.qmd
    - part: "Lecture 2"
      chapters:
        - lectures/lecture02/01-lecture02.qmd
        - lectures/lecture02/02-lecture02.qmd
    - part: "Lecture 3"
      chapters:
        - lectures/lecture03/01-lecture03.qmd
        - lectures/lecture03/02-lecture03.qmd
        - lectures/lecture03/03-lecture03.qmd
    - part: "Lecture 4"
      chapters:
        - lectures/lecture04/01-lecture04.qmd
        - lectures/lecture04/02-lecture04.qmd
    - part: "Lecture 5"
      chapters:
        - lectures/lecture05/0_input_output.qmd
        - lectures/lecture05/1-differentiation.qmd
    - part: "Lecture 6"
      chapters:
        - lectures/lecture06/2-integration.qmd
        - lectures/lecture06/3-solving_ODEs.qmd
    - part: "Seminar 2"
      chapters:
        - seminars/seminar02/md1.qmd
    - part: "Seminar 3"
      chapters:
        - seminars/seminar03/md2.qmd
    - part: "Seminar 4"
      chapters:
        - seminars/seminar04/md3.qmd
    - part: "Seminar 5"
      chapters:
        - seminars/seminar05/md4.qmd

format:
  pdf:
    documentclass: book
    papersize: a4
    toc: true
    number-sections: true
    number-depth: 2
    colorlinks: true
    geometry:
      - top=30mm
      - left=20mm
      - right=20mm
      - bottom=30mm
